import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Siderbar from "@/components/Siderbar";
import { getALlNotes } from "@/lib/redis";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex h-full bg-gray-50">
        <Siderbar></Siderbar> {children}
      </body>
    </html>
  );
}
